spring:
  application:
    name: ai_verify
  mail:
    web-application-type: reactive
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent
    key: AIzaSyDQQvrWMuUUe7K4JrDopyGG_M8zZMjywjw
  model: gemini-1.5-pro-latest
  temperature: 0.7
  max-tokens: 600



