import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { Cpu, FileText, BrainCircuit, ShieldCheck, ArrowRight, Sparkles, Layers, Shield } from 'lucide-react';

const fadeIn = {
  initial: { opacity: 0, y: 30 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] }
};

const staggerContainer = {
  animate: {
    transition: {
      staggerChildren: 0.1
    }
  }
};

export default function Product() {
  return (
    <div className="min-h-screen flex flex-col relative overflow-x-clip">
      <div className="absolute inset-0 bg-grid-pattern [mask-image:radial-gradient(ellipse_at_center,black,transparent_80%)] -z-10" />
      <div className="absolute top-1/4 right-0 w-[500px] h-[500px] opacity-20 pointer-events-none -z-10 bg-gradient-to-bl from-blue-400 to-transparent dark:from-blue-600 blur-[100px] rounded-full mix-blend-multiply dark:mix-blend-screen" />
      <div className="absolute bottom-1/4 left-0 w-[500px] h-[500px] opacity-20 pointer-events-none -z-10 bg-gradient-to-tr from-emerald-400 to-transparent dark:from-emerald-600 blur-[100px] rounded-full mix-blend-multiply dark:mix-blend-screen" />

      <Navbar />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-8 pt-24 pb-16 text-center relative z-10">
          <motion.div variants={staggerContainer} initial="initial" animate="animate" className="space-y-6">
            <motion.div variants={fadeIn} className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-card text-[11px] font-bold text-neutral-600 dark:text-neutral-300 uppercase tracking-widest">
              <Sparkles className="w-3.5 h-3.5 text-emerald-500 animate-pulse" /> Guardian Platform Suite
            </motion.div>

            <motion.h1 variants={fadeIn} className="font-display text-5xl md:text-8xl font-extrabold tracking-tighter leading-[0.9] text-gradient">
              The standard for <br /> content trust.
            </motion.h1>

            <motion.p variants={fadeIn} className="text-lg md:text-xl text-neutral-600 dark:text-neutral-400 max-w-3xl mx-auto leading-relaxed font-medium">
              Guardian integrates state-of-the-art classifier networks, linguistic perplexity models, and image forensics to expose AI-generated content and verify digital authenticity.
            </motion.p>
          </motion.div>
        </section>

        {/* Core Product Pillars */}
        <section className="max-w-7xl mx-auto px-8 py-16 relative z-10">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                title: "AI Text Classifier",
                desc: "Analyze sentence structures, semantic flow, perplexity, and burstiness to detect text generated by LLMs like ChatGPT, Claude, and Gemini with absolute precision.",
                icon: FileText,
                color: "from-blue-500/10 to-blue-500/5 dark:from-blue-500/20 dark:to-transparent",
                features: ["Perplexity & Burstiness Analysis", "Paragraph-level Heatmaps", "Multiple Language Support"]
              },
              {
                title: "Interactive AI Advisor",
                desc: "An intelligent, specialized chat interface providing real-time counsel on text origins, verification workflows, and policy guidelines.",
                icon: BrainCircuit,
                color: "from-purple-500/10 to-purple-500/5 dark:from-purple-500/20 dark:to-transparent",
                features: ["Context-aware Recommendations", "Document Verification Advice", "Integrations with Historical Scans"]
              },
              {
                title: "Developer APIs & SDKs",
                desc: "Embed enterprise-grade detection logic directly into your publishing flow, LMS, or CRM. Built for extreme concurrency and ultra-low response latencies.",
                icon: Layers,
                color: "from-amber-500/10 to-amber-500/5 dark:from-amber-500/20 dark:to-transparent",
                features: ["JSON REST Endpoints", "SDKs for Python & JS", "Rate-limit Tier Configurations"]
              }
            ].map((pillar, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="glass-card rounded-[2rem] p-8 md:p-10 flex flex-col justify-between hover:shadow-2xl hover:shadow-neutral-200/50 dark:hover:shadow-none transition-all duration-300 border border-neutral-200/30 group hover:-translate-y-1"
              >
                <div>
                  <div className="flex items-center gap-4 mb-6">
                    <div className="w-12 h-12 rounded-2xl bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 flex items-center justify-center shadow-lg transition-transform group-hover:scale-110">
                      <pillar.icon className="w-6 h-6" />
                    </div>
                    <h3 className="font-display text-2xl font-bold text-neutral-900 dark:text-white">{pillar.title}</h3>
                  </div>

                  <p className="text-neutral-600 dark:text-neutral-400 text-sm leading-relaxed mb-6 font-medium">
                    {pillar.desc}
                  </p>
                </div>

                <div className="space-y-3 pt-6 border-t border-neutral-100 dark:border-neutral-800">
                  {pillar.features.map((feat, idx) => (
                    <div key={idx} className="flex items-center gap-3 text-xs text-neutral-500 dark:text-neutral-400 font-semibold">
                      <ShieldCheck className="w-4 h-4 text-emerald-500" />
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Stats Section */}
        <section className="py-20 border-y border-neutral-200/50 dark:border-neutral-800/50 bg-white/20 dark:bg-black/20 backdrop-blur-sm relative z-10">
          <div className="max-w-7xl mx-auto px-8 grid grid-cols-2 md:grid-cols-4 gap-12 text-center">
            {[
              { val: "99.9%", label: "Detection Accuracy" },
              { val: "11ms", label: "Average Response Time" },
              { val: "10M+", label: "Scans Processed" },
              { val: "SOC-2", label: "Security Compliant" }
            ].map((stat, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                className="space-y-2"
              >
                <div className="font-display text-4xl md:text-5xl lg:text-6xl font-black text-neutral-900 dark:text-white tracking-tight">
                  {stat.val}
                </div>
                <div className="text-xs uppercase tracking-widest text-neutral-500 dark:text-neutral-400 font-bold">
                  {stat.label}
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        {/* Call to Action Section */}
        <section className="max-w-5xl mx-auto px-8 py-24 relative z-10 text-center">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="glass-card rounded-[3rem] p-10 md:p-16 border border-neutral-200/40 relative overflow-hidden"
          >
            <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/10 to-blue-500/10 opacity-30 pointer-events-none" />
            <div className="relative z-10 space-y-8">
              <h2 className="font-display text-4xl md:text-6xl font-bold tracking-tight text-neutral-900 dark:text-white">
                Verify content at scale.
              </h2>
              <p className="text-neutral-600 dark:text-neutral-400 max-w-xl mx-auto text-base font-medium leading-relaxed">
                Start securing your workflows against synthetic text and imagery. Get started with Guardian for free or contact our enterprise team.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link to="/signup" className="w-full sm:w-auto relative group overflow-hidden bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 px-8 py-4 rounded-full text-sm font-bold shadow-xl transition-all hover:scale-105 active:scale-95 flex items-center justify-center gap-2">
                  Get Started Free <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
                </Link>
                <Link to="/enterprise" className="w-full sm:w-auto px-8 py-4 rounded-full text-sm font-bold glass-card hover:bg-white/80 dark:hover:bg-[#222]/80 transition-all text-neutral-900 dark:text-white border border-neutral-200/50">
                  Talk to Sales
                </Link>
              </div>
            </div>
          </motion.div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
