package com.springboot.ai_verify.service;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.util.List;
import java.util.Map;

@Service
public class GeminiDetectionService {

    private static final Logger log = LoggerFactory.getLogger(GeminiDetectionService.class);
    private static final Duration REQUEST_TIMEOUT = Duration.ofSeconds(15);
    private final WebClient webClient;
    private final ObjectMapper objectMapper;

    @Value("${gemini.api.key:}")
    private String geminiApiKey;

    private static final String SYSTEM_PROMPT = """
        You are an advanced, professional Content Authenticity & Forensic Style Engine. Your job is to perform a rigorous linguistic and stylistic analysis of the provided text to determine the probability that it was generated by automated or synthetic models versus a human. Do NOT mention the term "AI", "artificial intelligence", or specific model names like "GPT", "ChatGPT", "Claude", "Gemini", etc., in your output analysis. Use terms like "automated content", "synthetic generation", "algorithmic patterns", or "templated style".

        Evaluate the text based on these specific dimensions:
        1. Perplexity: Measures word predictability and choice entropy. Synthetic/automated text typically exhibits low perplexity (predictable choices), whereas human writing has high perplexity.
        2. Burstiness: Measures sentence length and structure variance. Automated writing tends to be highly uniform (low burstiness), whereas humans naturally write with bursty, varying tempos.
        3. Consistency: Measures uniformity of tone and complexity. Automated text has high structural consistency, whereas humans fluctuate style naturally.

        You must provide your analysis strictly in the following JSON format. Do not include any other text or markdown wrappers outside the JSON:
        {
          "probability": 0-100, // Likelihood the text is automated/synthetic (100 = definitely automated, 0 = definitely human)
          "metrics": {
            "perplexity": 0-100, // Score representing word choice predictability (lower perplexity = higher predictability/match probability)
            "burstiness": 0-100, // Score representing rhythm variance (lower burstiness = more uniform/match probability)
            "consistency": 0-100 // Score representing style uniformity (higher consistency = single style/match probability)
          },
          "patterns": ["pattern1", "pattern2", "pattern3"], // List 2-4 observed patterns that support your score
          "analysis": "Provide a comprehensive, professional explanation (2-3 sentences) detailing why the text was classified as human or automated/synthetic, citing specific lexical or rhythmic evidence from the text."
        }
        """;

    public GeminiDetectionService(WebClient.Builder webClientBuilder, ObjectMapper objectMapper) {
        this.webClient = webClientBuilder.build();
        this.objectMapper = objectMapper;
    }

    public record GeminiPart(String text) {}
    public record GeminiContent(String role, List<GeminiPart> parts) {}
    public record GeminiInstruction(List<GeminiPart> parts) {}
    public record GeminiGenerationConfig(String responseMimeType) {}
    public record GeminiRequest(
            List<GeminiContent> contents,
            GeminiInstruction systemInstruction,
            GeminiGenerationConfig generationConfig
    ) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record GeminiResponse(List<Candidate> candidates) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Candidate(Content content) {}

    @JsonIgnoreProperties(ignoreUnknown = true)
    public record Content(List<GeminiPart> parts) {}

    public Mono<String> detectAiContent(String textToAnalyze) {
        if (geminiApiKey == null || geminiApiKey.isBlank()) {
            log.warn("AI detection attempted but Gemini API key is not configured");
            return Mono.just(errorJson("The Gemini AI detection service is not configured."));
        }

        List<GeminiContent> contents = List.of(
            new GeminiContent("user", List.of(new GeminiPart(textToAnalyze)))
        );
        
        GeminiInstruction sysInstr = new GeminiInstruction(List.of(new GeminiPart(SYSTEM_PROMPT)));
        GeminiGenerationConfig genConfig = new GeminiGenerationConfig("application/json");
        GeminiRequest payload = new GeminiRequest(contents, sysInstr, genConfig);

        String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + geminiApiKey;

        return webClient.post()
                .uri(url)
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(payload)
                .retrieve()
                .bodyToMono(GeminiResponse.class)
                .timeout(REQUEST_TIMEOUT)
                .map(response -> {
                    if (response.candidates() != null && !response.candidates().isEmpty() &&
                        response.candidates().getFirst().content() != null &&
                        response.candidates().getFirst().content().parts() != null &&
                        !response.candidates().getFirst().content().parts().isEmpty()) {
                        
                        String jsonResponse = response.candidates().getFirst().content().parts().getFirst().text();
                        
                        // Strip markdown formatting if any
                        jsonResponse = jsonResponse.trim();
                        if (jsonResponse.startsWith("```json")) {
                            jsonResponse = jsonResponse.substring(7);
                            if (jsonResponse.endsWith("```")) {
                                jsonResponse = jsonResponse.substring(0, jsonResponse.length() - 3);
                            }
                        } else if (jsonResponse.startsWith("```")) {
                            jsonResponse = jsonResponse.substring(3);
                            if (jsonResponse.endsWith("```")) {
                                jsonResponse = jsonResponse.substring(0, jsonResponse.length() - 3);
                            }
                        }
                        jsonResponse = jsonResponse.trim();
                        
                        // Validate JSON
                        try {
                            objectMapper.readTree(jsonResponse);
                            return jsonResponse;
                        } catch (JsonProcessingException e) {
                            log.error("Failed to parse JSON response from Gemini: {}", jsonResponse, e);
                            return errorJson("The AI model returned malformed JSON.");
                        }
                    }
                    return errorJson("The AI model returned an empty response.");
                })
                .onErrorResume(e -> {
                    log.error("Error calling Gemini API: {}", e.getMessage(), e);
                    if (e instanceof WebClientResponseException wcre) {
                        if (wcre.getStatusCode() == HttpStatus.UNAUTHORIZED) {
                            return Mono.just(errorJson("The Gemini API key is invalid. Please check your configuration."));
                        }
                    }
                    return Mono.just(errorJson("The AI service is currently unavailable. Please try again later."));
                });
    }

    private String errorJson(String message) {
        try {
            return objectMapper.writeValueAsString(Map.of("error", message));
        } catch (JsonProcessingException e) {
            return "{\"error\": \"An unexpected error occurred.\"}";
        }
    }
}
