package com.springboot.ai_verify.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientRequestException;
import org.springframework.web.reactive.function.client.WebClientResponseException;
import reactor.core.publisher.Mono;
import reactor.util.retry.Retry;

import java.io.IOException;
import java.time.Duration;
import java.util.List;
import java.util.Objects;
import java.net.SocketException;
import java.util.concurrent.TimeoutException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class NvidiaDetectionService {

    private static final Logger log = LoggerFactory.getLogger(NvidiaDetectionService.class);
    private static final Duration REQUEST_TIMEOUT = Duration.ofSeconds(30);
    private static final Duration RETRY_BACKOFF = Duration.ofSeconds(2);
    private static final int MAX_RETRIES = 2;
    private static final double RETRY_JITTER = 0.5;

    private static final String SYSTEM_PROMPT = """
        Analyze the given text and assess the likelihood that it was generated by an AI versus a human.
        Provide ONLY a JSON response in this exact format. All newlines inside JSON string values (e.g., in the 'analysis' field) MUST be escaped as \n. All double quotes inside any JSON string value MUST be escaped as ".
        {
          "probability": 0-100,
          "metrics": {
            "perplexity": 0-100,
            "burstiness": 0-100,
            "consistency": 0-100
          },
          "patterns": ["pattern1", "pattern2", ...],
          "analysis": "Detailed explanation of the findings, summarizing why the text is likely AI or human-written based on the metrics."
        }
        """;

    private final WebClient webClient;
    private final ObjectMapper objectMapper;

    @Value("${nvidia.api.url:https://integrate.api.nvidia.com/v1/chat/completions}")
    private String nvidiaApiUrl;

    @Value("${nvidia.api.key:}")
    private String nvidiaApiKey;

    @Value("${nvidia.detection.model:meta/llama-3.1-70b-instruct}")
    private String detectionModel;

    private static final List<String> FALLBACK_MODELS = List.of(
            "meta/llama-3.1-70b-instruct",
            "nvidia/llama-3.1-nemotron-70b-instruct",
            "mistralai/mixtral-8x22b-instruct-v0.1"
    );

    public NvidiaDetectionService(WebClient.Builder webClientBuilder, ObjectMapper objectMapper) {
        this.webClient = webClientBuilder.build();
        this.objectMapper = objectMapper;
    }

    public record NvidiaMessage(String role, String content) {}
    
    public record NvidiaDetectionRequest(
            String model,
            List<NvidiaMessage> messages,
            double temperature,
            int max_new_tokens
    ) {}
    
    public record NvidiaResponse(List<Choice> choices) {}
    
    public record Choice(NvidiaMessage message) {}

    public Mono<String> detectAiContent(String textToAnalyze) {
        if (nvidiaApiKey == null || nvidiaApiKey.isBlank()) {
            log.warn("AI detection attempted but NVIDIA API key is not configured");
            return Mono.just("{\"error\": \"The NVIDIA AI detection service is not configured.\"}");
        }

        List<NvidiaMessage> messages = List.of(
                new NvidiaMessage("system", SYSTEM_PROMPT),
                new NvidiaMessage("user", textToAnalyze)
        );
        
        return detectWithModelCandidates(messages)
                .map(this::processNvidiaResponse)
                .onErrorResume(e -> {
                    log.error("Error calling NVIDIA API: {}", e.getMessage(), e);
                    if (e instanceof WebClientResponseException wcre) {
                        if (wcre.getStatusCode() == HttpStatus.UNAUTHORIZED) {
                            return Mono.just("{\"error\": \"The NVIDIA API key is invalid. Please check your configuration.\"}");
                        }
                        log.error("NVIDIA API Error Status: {}", wcre.getStatusCode());
                        log.debug("NVIDIA API Error Response: {}", wcre.getResponseBodyAsString());
                    }
                    return Mono.just("{\"error\": \"The NVIDIA AI service is currently unavailable. Please try again later.\"}");
                });
    }

    private Mono<NvidiaResponse> detectWithModelCandidates(List<NvidiaMessage> messages) {
        List<String> candidates = new java.util.ArrayList<>();
        if (detectionModel != null && !detectionModel.isBlank()) {
            candidates.add(detectionModel.trim());
        }
        FALLBACK_MODELS.stream()
                .filter(Objects::nonNull)
                .map(String::trim)
                .filter(model -> !model.isEmpty() && !candidates.contains(model))
                .forEach(candidates::add);

        return tryNextModel(candidates, messages);
    }

    private Mono<NvidiaResponse> tryNextModel(List<String> models, List<NvidiaMessage> messages) {
        if (models.isEmpty()) {
            return Mono.error(new IllegalStateException("No NVIDIA models are configured."));
        }

        String model = models.getFirst();
        NvidiaDetectionRequest payload = new NvidiaDetectionRequest(model, messages, 0.7, 500);

        return webClient.post()
                .uri(nvidiaApiUrl)
                .header("Authorization", "Bearer " + nvidiaApiKey)
                .header("Accept", "application/json")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(payload)
                .retrieve()
                .bodyToMono(NvidiaResponse.class)
                .timeout(REQUEST_TIMEOUT)
                .retryWhen(Retry.backoff(MAX_RETRIES, RETRY_BACKOFF)
                        .jitter(RETRY_JITTER)
                        .filter(NvidiaDetectionService::isRetryableError)
                        .onRetryExhaustedThrow((retryBackoffSpec, retrySignal) -> retrySignal.failure()))
                .onErrorResume(WebClientResponseException.NotFound.class, ex -> {
                    if (models.size() <= 1) {
                        return Mono.error(ex);
                    }
                    String responseBody = ex.getResponseBodyAsString();
                    log.warn("NVIDIA model '{}' was not found; trying fallback model. Response: {}", model, responseBody);
                    return tryNextModel(models.subList(1, models.size()), messages);
                });
    }

    private String processNvidiaResponse(NvidiaResponse apiResponse) {
        if (apiResponse == null || apiResponse.choices() == null || apiResponse.choices().isEmpty()) {
            log.warn("NVIDIA API returned empty response");
            return "{\"error\": \"The NVIDIA AI model returned an empty response.\"}";
        }

        Choice firstChoice = apiResponse.choices().getFirst();
        if (firstChoice.message() == null || firstChoice.message().content() == null ||
            firstChoice.message().content().isBlank()) {
            log.warn("NVIDIA API returned message with no content");
            return "{\"error\": \"The NVIDIA AI model returned a message with no content.\"}";
        }

        String content = firstChoice.message().content().trim();
        int jsonStart = content.indexOf('{');
        int jsonEnd = content.lastIndexOf('}');

        if (jsonStart == -1 || jsonEnd == -1 || jsonEnd <= jsonStart) {
            log.error("Failed to find JSON in NVIDIA response: {}", content);
            return "{\"error\": \"Could not find a valid JSON object in the AI's response.\"}";
        }

        String extractedJson = content.substring(jsonStart, jsonEnd + 1);

        try {
            objectMapper.readTree(extractedJson);
            return extractedJson;
        } catch (JsonProcessingException e) {
            log.debug("Initial JSON parse failed, attempting repair...");
            return attemptJsonRepair(extractedJson);
        }
    }

    private String attemptJsonRepair(String json) {
        // Step 1: Remove non-printable characters except newline, tab
        String cleaned = json.replaceAll("[\\x00-\\x08\\x0B\\x0C\\x0E-\\x1F]", "");
        
        // Step 2: Fix unescaped newlines in string values (within quotes)
        // This replaces literal newlines with \n escape sequences
        cleaned = cleaned.replaceAll("\"([^\"]*?)\\n([^\"]*?)\"", "\"$1\\\\n$2\"");
        cleaned = cleaned.replaceAll("\"([^\"]*?)\\r\\n([^\"]*?)\"", "\"$1\\\\n$2\"");
        
        // Step 3: Fix unescaped quotes within strings (but not already escaped)
        // Look for quotes that aren't preceded by backslash
        cleaned = cleaned.replaceAll("(?<!\\\\)\"([^\"]*?)\"([^\"]*?)\"", "\"$1\\\\\"$2\"");
        
        // Step 4: Replace single quotes with double quotes (common issue)
        // But be careful around contractions - only replace quote pairs
        Pattern singleQuotePattern = Pattern.compile("'([^']*?)'");
        Matcher singleQuoteMatcher = singleQuotePattern.matcher(cleaned);
        StringBuilder sb = new StringBuilder();
        while (singleQuoteMatcher.find()) {
            String content = singleQuoteMatcher.group(1);
            // Escape any double quotes inside
            content = content.replace("\"", "\\\"");
            singleQuoteMatcher.appendReplacement(sb, "\"" + content + "\"");
        }
        singleQuoteMatcher.appendTail(sb);
        cleaned = sb.toString();
        
        // Step 5: Add missing commas between properties
        cleaned = cleaned.replaceAll("(\"\\s*})", "$1");
        cleaned = cleaned.replaceAll("([}\\]])\\s*([{\\[])", "$1,$2");
        cleaned = cleaned.replaceAll("(\\d|\"true\"|\"false\"|null)\\s*([{\\[\"])", "$1,$2");
        
        // Step 6: Fix trailing commas before closing brackets
        cleaned = cleaned.replaceAll(",\\s*([}\\]])", "$1");

        try {
            objectMapper.readTree(cleaned);
            log.debug("Successfully repaired malformed JSON");
            return cleaned;
        } catch (JsonProcessingException ex) {
            log.error("JSON repair failed after comprehensive attempts. Raw: {}", json);
            log.error("Attempted repair result: {}", cleaned);
            return "{\"error\": \"The NVIDIA AI model returned malformed JSON that could not be fixed.\"}";
        }
    }

    private static boolean isRetryableError(Throwable throwable) {
        if (throwable instanceof WebClientResponseException wcre) {
            int statusCode = wcre.getStatusCode().value();
            return statusCode == 429 || (statusCode >= 500 && statusCode < 600);
        }

        if (throwable instanceof TimeoutException || throwable instanceof WebClientRequestException) {
            Throwable cause = throwable.getCause();
            return cause == null || cause instanceof IOException || cause instanceof SocketException;
        }

        Throwable cause = throwable.getCause();
        return cause instanceof IOException || cause instanceof SocketException;
    }
}
