spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      max-lifetime: 1200000
      idle-timeout: 600000
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

mistral:
  api:
    url: ${MISTRAL_API_URL:https://api.mistral.ai/v1/chat/completions}
    key: ${MISTRAL_API_KEY:}
  detection:
    model: ${MISTRAL_DETECTION_MODEL:mistral-large-latest}

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never